package fabiel.casas.rijksmuseumapp.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFE5C43F)
val md_theme_dark_onPrimary = Color(0xFF5F112A)
val md_theme_dark_primaryContainer = Color(0xFFFFE173)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9DF)
val md_theme_dark_secondary = Color(0xFF7A5C61)
val md_theme_dark_onSecondary = Color(0xFF3B2F00)
val md_theme_dark_secondaryContainer = Color(0xFF554500)
val md_theme_dark_onSecondaryContainer = Color(0xFF7C2940)
val md_theme_dark_tertiary = Color(0xFFA2C9FF)
val md_theme_dark_onTertiary = Color(0xFF00315B)
val md_theme_dark_tertiaryContainer = Color(0xFF004881)
val md_theme_dark_onTertiaryContainer = Color(0xFFD3E4FF)
val md_theme_dark_error = Color(0xFFFFB2BC)
val md_theme_dark_errorContainer = Color(0xFF8D0F36)
val md_theme_dark_onError = Color(0xFF670023)
val md_theme_dark_onErrorContainer = Color(0xFFFFD9DD)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE9E1D8)
val md_theme_dark_outline = Color(0xFF9F8D83)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE9E1D8)
val md_theme_dark_inversePrimary = Color(0xFF9A4057)
val md_theme_dark_surfaceTint = Color(0xFFFFB1C0)
val md_theme_dark_outlineVariant = Color(0xFF52443B)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF16130E)
val md_theme_dark_onSurface = Color(0xFFCDC5BD)
val md_theme_dark_surfaceVariant = Color(0xFF52443B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C3B7)
